import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.homeContainer}>
          <h1>Welcome to My Application</h1>
          <p>In this website, we will be building a NextJs Application</p>
          <h5>Press <Link href='/posts/Home'>HERE</Link> to start</h5>
        </div>
      </main>
    </>
  )
}
